# Generated by Django 4.2.15 on 2024-09-22 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visanews', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='visanewsarticle',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='visanews_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='visanewsarticle',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visanews_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='visanewsarticle',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='visanews_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
