# Generated by Django 4.2.15 on 2024-09-26 14:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visanews', '0003_visanewsarticle_dislikes_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visanewsarticle',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
