# Generated by Django 4.2.15 on 2024-09-26 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visanews', '0004_visanewsarticle_featured_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visanewsarticle',
            old_name='featured_image',
            new_name='visanews_image',
        ),
    ]
