# Generated by Django 4.2.15 on 2024-09-10 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visa_app', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
